service: books-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:CreateTable
        - dynamodb:DeleteItem  # Dodaj to uprawnienie
        - dynamodb:DescribeTable  # Dodaj to uprawnienie
      Resource: "*"

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Books
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  list:
    handler: bookHandler.list
    events:
      - http:
          path: /books
          method: get

  get:
    handler: bookHandler.get
    events:
      - http:
          path: /books/{id}
          method: get
    
  post:
    handler: bookHandler.create
    events:
      - http:
          path: /books
          method: post
  put:
    handler: bookHandler.createOrUpdate
    events:
      - http:
          path: /books/{id}
          method: put
  delete:
    handler: bookHandler.deleteById
    events:
      - http:
          path: /books/{id}
          method: delete